export * from './common';
export { default as Header } from './Header';
export { default as Main } from './Main';
export { default as Onboarding } from './Onboarding';
export { default as SignIn } from './SignIn';
export { default as SignUp } from './SignUp';
export { default as Writing } from './Writing';
export { default as Posting } from './Posting';
export { default as Thumbnail } from './Thumbnail';
export { default as Mypage } from './MyPage';